Richard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('home.urls')),
	path('pizza', include('pizza.urls', namespace="pizza")),
    path('primer', include('primer.urls', namespace="primer")),    
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path
from . import views

# Create your views here.
urlpatterns = [
	path("", views.index, name="index")
]

pizza/urls.py
from django.urls import path
from . import views

# Create your views here.
app_name = "pizza"
urlpatterns = [
	path("", views.pizza, name="pizza"),
	path("create", views.create, name="create"),
	path("other/<pk>", views.other, name="other"),
	path("login", views.login_view, name="login"),
	path("logout", views.logout_view, name="logout"),
	path("specialty/<pk>", views.specialty, name="specialty"),
	path("register", views.register, name="register"),
	path("cart", views.get_cart, name="cart"),
	path("confirmation", views.confirmation, name="confirmation"),
]

pizza/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class SpecialtySizePrice(models.Model):
    SMALL = "S"
    MEDIUM = "M"
    LARGE = "L"
    XLARGE = "XL"
    SIZE_CHOICES = (
        (SMALL, "Small"),
        (MEDIUM, "Medium"),
        (LARGE, "Large"),
        (XLARGE, "Extra Large"),
    )
    size = models.CharField(
        max_length=64,
        choices=SIZE_CHOICES,
        default=SMALL,
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.size} for ${self.price}"

class SpecialtyPizza(models.Model):
    name = models.CharField(max_length=64)
    description = models.CharField(max_length=256, blank=True, null=True)
    size = models.CharField(max_length=64, blank=True, null=True)

    def __str__(self):
        return f"{self.name}"


class OtherItem(models.Model):
    CALZONE = "CZ"
    SANDWICH = "SW"
    SALAD = "SL"
    APPETIZER = "AP"
    CATEGORY_CHOICES = (
        (CALZONE, "Calzone"),
        (SANDWICH, "Sandwich"),
        (SALAD, "Salad"),
        (APPETIZER, "Appetizer"),
    )
    name = models.CharField(max_length=64)
    category = models.CharField(
        max_length=64,
        choices=CATEGORY_CHOICES,
        default=SANDWICH,
    )
    description = models.CharField(max_length=256, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.name}"


class Topping(models.Model):
    MEAT = "M"
    VEGETABLES = "V"
    OTHERS = "O"
    TYPE_CHOICES = (
        (MEAT, "Meat"),
        (VEGETABLES, "Vegetables"),
        (OTHERS, "Others"),
    )
    name = models.CharField(max_length=32)
    type = models.CharField(
        max_length=16,
        choices=TYPE_CHOICES,
        default=MEAT,
    )

    def __str__(self):
        return f"{self.name}"

class CreatePizza(models.Model):
    SMALL = "S"
    MEDIUM = "M"
    LARGE = "L"
    XLARGE = "XL"
    SIZE_CHOICES = (
        (SMALL, "Small"),
        (MEDIUM, "Medium"),
        (LARGE, "Large"),
        (XLARGE, "Extra Large"),
    )
    size = models.CharField(
        max_length=64,
        choices=SIZE_CHOICES,
        default=SMALL,
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    topping_price = models.DecimalField(max_digits=10, decimal_places=2)
    toppings = models.ManyToManyField(Topping, blank=True, related_name="createpizza")

    def __str__(self):
        return f"{self.size} for ${self.price}. Each additional topping for {self.topping_price}"

class Item(models.Model):
    name = models.CharField(max_length=64)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField(max_length=100)
    size = models.CharField(max_length=16, blank=True, null=True)

    def __str__(self):
        return f"{self.quantity} {self.name} at {self.price}"

class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    OPEN = "O"
    CLOSED = "C"
    STATUS_CHOICES = (
        (OPEN, "Open"),
        (CLOSED, "Closed"),
    )
    status = models.CharField(
        max_length=8,
        choices=STATUS_CHOICES,
        default=OPEN,
    )
    items = models.ManyToManyField(Item, blank=True, related_name="cart")

    def __str__(self):
        return f"{self.status} cart for {self.user}"

pizza/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist

from .models import SpecialtyPizza, SpecialtySizePrice, OtherItem, Topping, CreatePizza, Cart, Item

# Create your views here.
def pizza(request):
	if not request.user.is_authenticated:
		return render(request, "pizza/login.html", {"message": None})

	try:
		c = Cart.objects.get(user=request.user, status=Cart.OPEN)
		num_items = 0
		for i in c.items.all():
			num_items += i.quantity
	except ObjectDoesNotExist:
		c = Cart(user=request.user)
		c.save()
		num_items = 0

	if request.method == "POST":
		num_items += 1
		category = request.POST["category"]
		if (category == "specialty"):
			pizza = SpecialtyPizza.objects.get(pk=request.POST["pk"])
			name = pizza.name
			size = request.POST["size"]
			quantity = request.POST["quantity"]
			s = SpecialtySizePrice.objects.get(size = size)
			price = s.price
			try:
				item = Item.objects.get(name=name, size=size)
				item.quantity += quantity
			except ObjectDoesNotExist:
				item = Item(name=name, price=price, size=size, quantity=quantity)

			item.save()
			c.items.add(item)
		elif (category == "other"):
			pk = request.POST["pk"]
			quantity = request.POST["quantity"]
			other = OtherItem.objects.get(pk=pk)
			name = other.name
			price = other.price
			try:
				item = Item.objects.get(name=name)
				item.quantity += quantity
			except ObjectDoesNotExist:
				item = Item(name=name, price=price, quantity=quantity)

			item.save()
			c.items.add(item)
		else:
			s = request.POST["size"]
			pizza = CreatePizza.objects.get(size=s)
			size = pizza.size
			toppings = request.POST.getlist("topping_pk")
			numToppings = 0
			for t in toppings:
				numToppings += 1
			name = f"{size} Pizza"
			price = pizza.price + (numToppings * pizza.topping_price)
			item = Item(name=name, price=price, quantity=1)
			item.save()
			c.items.add(item)

		c.save()
		return HttpResponseRedirect(reverse("pizza:pizza"))

	context = get_menu()
	context["item_count"] = num_items
	return render(request, "pizza/pizza.html", context)

def specialty(request, pk):
	c = Cart.objects.get(user=request.user, status=Cart.OPEN)
	num_items = 0
	for i in c.items.all():
		num_items += i.quantity

	pizza = SpecialtyPizza.objects.get(pk=pk)
	context = {
		"pk": pizza.pk,
		"name": pizza.name,
		"category": "specialty",
		"prices": SpecialtySizePrice.objects.all(),
		"item_count": num_items
	}
	return render(request, "pizza/specialty.html", context)

def create(request):
	c = Cart.objects.get(user=request.user, status=Cart.OPEN)
	num_items = 0
	for i in c.items.all():
		num_items += i.quantity

	context = {
		"sizes": CreatePizza.objects.all(),
		"category": "create",
		"meats": Topping.objects.filter(type=Topping.MEAT),
		"veggies": Topping.objects.filter(type=Topping.VEGETABLES),
		"others": Topping.objects.filter(type=Topping.OTHERS),
		"item_count": num_items
	}
	return render(request, "pizza/create.html", context)

def other(request, pk):
	c = Cart.objects.get(user=request.user, status=Cart.OPEN)
	num_items = 0
	for i in c.items.all():
		num_items += i.quantity

	item = OtherItem.objects.get(pk=pk)
	context = {
		"pk": item.pk,
		"name": item.name,
		"description": item.description,
		"category": "other",
		"price": item.price,
		"item_count": num_items
	}
	return render(request, "pizza/other.html", context)

def get_menu():
	context = {
		"spizza": SpecialtyPizza.objects.all(),
		"spizza_prices": SpecialtySizePrice.objects.all(),
		"small": CreatePizza.objects.get(size=CreatePizza.SMALL),
		"medium": CreatePizza.objects.get(size=CreatePizza.MEDIUM),
		"large": CreatePizza.objects.get(size=CreatePizza.LARGE),
		"xlarge": CreatePizza.objects.get(size=CreatePizza.XLARGE),
		"calzone": OtherItem.objects.filter(category=OtherItem.CALZONE),
		"sandwich": OtherItem.objects.filter(category=OtherItem.SANDWICH),
		"salad": OtherItem.objects.filter(category=OtherItem.SALAD),
		"appetizer": OtherItem.objects.filter(category=OtherItem.APPETIZER),
	}
	return context

def get_cart(request):
	try:
		c = Cart.objects.get(user=request.user, status=Cart.OPEN)
	except ObjectDoesNotExist:
		return

	if request.method == "POST":
		pk = request.POST["remove"]
		item = Item.objects.get(pk=pk)
		item.delete()

	total = 0
	num_items = 0
	for i in c.items.all():
		total += i.quantity * i.price
		num_items += i.quantity

	context = {
		"items": c.items.all(),
		"total": total,
		"item_count": num_items,
	}

	return render(request, "pizza/cart.html", context)

def confirmation(request):
	c = Cart.objects.get(user=request.user, status=Cart.OPEN)
	c.status=Cart.CLOSED
	c.save()

	return render(request, "pizza/confirmation.html", {"item_count": 0})

def login_view(request):
	#Add try, except later
	username = request.POST["username"]
	password = request.POST["password"]
	user = authenticate(request, username=username, password=password)
	if user is not None:
		login(request, user)
		return HttpResponseRedirect(reverse("pizza:pizza"))
	else:
		return render(request, "pizza/login.html", {"message": "Invalid credentials"})

def logout_view(request):
	logout(request)
	return render(request, "pizza/login.html", {"message": "Logged out"})

def register(request):
	password = request.POST["pwd1"]
	password2 = request.POST["pwd2"]
	if (password != password2):
		return render(request, "pizza/login.html", {"message": "Your passwords do not match"})

	username = request.POST["uname"]
	if User.objects.filter(username=username).exists():
		return render(request, "pizza/login.html", {"message": "Username is already taken"})

	firstname = request.POST["fname"]
	lastname = request.POST["lname"]
	email = request.POST["email"]
	user = User.objects.create_user(username, email, password)
	user.first_name = firstname
	user.last_name = lastname
	user.save()
	login(request, user)
	return HttpResponseRedirect(reverse("pizza:pizza"))

pizza/templates/pizza/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Stuft Pizza</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'pizza/css/style.css' %}">
</head>
<body>
	<div class="topnav">
  		<a href="{% url 'pizza:pizza' %}">Stuft Pizza</a>
		<div class="topnav-right">
	  		<a href="{% url 'pizza:cart' %}"><span class="glyphicon glyphicon-shopping-cart"></span>{{ item_count }} Items</a>
		</div>
	</div>

	<div class="body">
	{% block body %}
	{% endblock %}
	</div>

	<div class="container" align="right">
		<h5>Currently logged in as: {{ user.username }}</h5>
		<h5><a href="{% url 'pizza:logout' %}">Logout</a></h5>
	</div>

</body>
</html>

pizza/templates/pizza/cart.html
{% extends "pizza/base.html" %}

{% block body %}
<div class="container cart" align="center">
    <table class="table" style="width:50%">
        <thead>
            <tr>
                <th>Item</th>
                <th>Quantity</th>
                <th>Price</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for i in items %}
            <tr>
                {% if i.size != None %}
                <td>{{ i.size }} {{ i.name }}</td>
                {% else %}
                <td>{{ i.name }}</td>
                {% endif %}
                <td>{{ i.quantity }}</td>
                <form action="{% url 'pizza:cart' %}" method="post">
                    {% csrf_token %}
                    <td><button class="btn btn-primary" name="remove" value="{{ i.pk }}">Remove</button></td>
                </form>
                <td>${{ i.price }}</td>
            </tr>
            {% endfor %}
            <tr>
                <td>Total</td>
                <td></td>
                <td></td>
                <td>${{ total }}</td>
            </tr>
        </tbody>
    </table>
    <form action="{% url 'pizza:confirmation' %}">
        <p align="center"><button class="btn btn-primary">Complete Purchase</button></p>
    </form>
</div>

{% endblock %}

pizza/templates/pizza/confirmation.html
{% extends "pizza/base.html" %}

{% block body %}
<h3>Your order has been purchased!</h3>

{% endblock %}

pizza/templates/pizza/create.html
{% extends "pizza/base.html" %}

{% block body %}
<div class="createpage">
    <h1>Create Your Pizza</h1>
    <form action="{% url 'pizza:pizza' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="category" value="{{ category }}"/>
        <div class="form-group">
            <label for="size">Select a Size</label>
            <select class="form-control" id="size" name="size">
                {% for i in sizes %}
                <option value="{{ i.size }}">{{ i }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="row">
            <h5>Select Ingredients</h5>
            <div class="col-lg-4">
                <h3>Meats</h3>
                {% for topping in meats %}
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="topping_pk" value="{{ topping.pk }}" id="{{ topping.name }}">
                    <label class="form-check-label" for="{{ topping.name }}">
                        {{ topping.name }}
                    </label>
                </div>
                {% endfor %}
            </div>
            <div class="col-lg-4">
                <h3>Vegetables</h3>
                {% for topping in veggies %}
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="topping_pk" value="{{ topping.pk }}" id="{{ topping.name }}">
                    <label class="form-check-label" for="{{ topping.name }}">
                        {{ topping.name }}
                    </label>
                </div>
                {% endfor %}
            </div>
            <div class="col-lg-4">
                <h3>Other</h3>
                {% for topping in others %}
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="topping_pk" value="{{ topping.pk }}" id="{{ topping.name }}">
                    <label class="form-check-label" for="{{ topping.name }}">
                        {{ topping.name }}
                    </label>
                </div>
                {% endfor %}
            </div>
        </div>

        <p align="center"><button class="btn btn-primary">Add to Cart</button></p>

    </form>
</div>
{% endblock %}

pizza/templates/pizza/login.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>Stuft Pizza</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="{% static 'pizza/css/style.css' %}">
	</head>
	<body>
		<div class="container">
			{% if message %}
			<div>
				{{ message }}
			</div>
			{% endif %}

			<div class="row">
				<div class="col-lg-6">
					<h3>Login</h3>
					<form action="{% url 'pizza:login' %}" method="post">
						{% csrf_token %}
						<div class="form-group">
							<label for="username">Username</label>
							<input name="username" id="username" class="form-control" type="text"/>
						</div>
						<div class="form-group">
							<label for="password">Password</label>
							<input name="password" id="password" class="form-control" type="password"/>
						</div>
						<button type="submit" class="btn btn-primary">Login</button>
					</form>
				</div>
				<div class="col-lg-6">
					<h3>Register</h3>
					<form action="{% url 'pizza:register' %}" method="post">
						{% csrf_token %}
						<div class="form-group">
							<label for="uname">Username</label>
							<input name="uname" id="uname" class="form-control" type="text"/>
						</div>
						<div class="form-group">
							<label for="pwd1">Password</label>
							<input name="pwd1" id="pwd1" class="form-control" type="password"/>
						</div>
						<div class="form-group">
							<label for="pwd2">Re-enter Your Password</label>
							<input name="pwd2" id="pwd2" class="form-control" type="password"/>
						</div>
						<div class="form-group">
							<label for="fname">First Name</label>
							<input name="fname" id="fname" class="form-control" type="text"/>
						</div>
						<div class="form-group">
							<label for="lname">Last Name</label>
							<input name="lname" id="lname" class="form-control" type="text"/>
						</div>
						<div class="form-group">
							<label for="email">Email</label>
							<input name="email" id="email" class="form-control" type="email"/>
						</div>
						<button type="submit" class="btn btn-primary">Register</button>
					</form>
				</div>
			</div>
		</div>
	</body>
</html>

pizza/templates/pizza/other.html
{% extends "pizza/base.html" %}

{% block body %}
<div class="otheritem">
    <h1>{{ name }}</h1>
    {% if description != None %}
    <p>{{ description }}</p>
    {% endif %}

    <p>{{ price }}</p>
    <form action="{% url 'pizza:pizza' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="pk" value="{{ pk }}"/>
        <input type="hidden" name="category" value="{{ category }}"/>
        <div class="form-group">
            <label for="quantity">Select a Quantity</label>
            <input class="form-control" type="number" value="{{ i.quantity }}" id="quantity" name="quantity" min="0">
        </div>
        <p align="center"><button class="btn btn-primary">Add to Cart</button></p>
    </form>
</div>

{% endblock %}

pizza/templates/pizza/pizza.html
{% extends "pizza/base.html" %}

{% block body %}
<div class="top">
	<div class="subheader">A Place for Pizza, Beer, and Football</div>

	<div class="category">
		<h3>Specialty Pizzas</h3>
		<div class="sizeandprice">
			{% for i in spizza_prices %}
			<div class="sizeandprices">
				{{ i.size }} {{ i.price }}
			</div>
			{% endfor %}
		</div>
		<div class="row">
			{% for p in spizza %}
			<div class="col col-lg-4 menu4">
				<a href="{% url 'pizza:specialty' pk=p.pk %}">
					<h4>{{ p.name }}</h4>
					<p>{{ p.description }}</p>
				</a>
			</div>
			{% endfor %}
		</div>
	</div>

	<div class="category">
		<h3>Create Your Own Pizza</h3>
		<div class="createpizza">
			<h4>{{ small }}</h4>
			<h4>{{ medium }}</h4>
			<h4>{{ large }}</h4>
			<h4>{{ xlarge }}</h4>
		</div>

		<a href="{% url 'pizza:create' %}">
			<div class="create">
				<h4>Create Now</h4>
			</div>
		</a>
	</div>
</div>

<div class="bottom">
	<div class="category">
		<h3>Calzones</h3>
		<div class="row">
			{% for i in calzone %}
			<div class="col col-lg-4 menu4">
				<a href="{% url 'pizza:other' pk=i.pk %}">
					<h4>{{ i.name }}</h4>
					<p>{{ i.description }} {{ i.price }}</p>
				</a>
			</div>
			{% endfor %}
		</div>
	</div>

	<div class="category">
		<h3>Hot "Stuft" Sandwiches</h3>
		<div class="row">
			{% for i in sandwich %}
			<div class="col col-lg-4 menu4">
				<a href="{% url 'pizza:other' pk=i.pk %}">
					<h4>{{ i.name }}</h4>
					<p>{{ i.price }}</p>
				</a>
			</div>
			{% endfor %}
		</div>
	</div>

	<div class="category">
		<h3>Fresh Salads</h3>
		<div class="row">
			{% for i in salad %}
			<div class="col col-lg-4 menu4">
				<a href="{% url 'pizza:other' pk=i.pk %}">
					<h4>{{ i.name }}</h4>
					<p>{{ i.description }} {{ i.price }}</p>
				</a>
			</div>
			{% endfor %}
		</div>
	</div>

	<div class="category">
		<h3>Appetizers</h3>
		<div class="row">
			{% for i in appetizer %}
			<div class="col col-lg-4 menu4">
				<a href="{% url 'pizza:other' pk=i.pk %}">
					<h4>{{ i.name }}</h4>
					<p>{% if i.description != None %}{{ i.description }}{% endif %} {{ i.price }}</p>
				</a>
			</div>
			{% endfor %}
		</div>
	</div>
</div>

{% endblock %}

pizza/templates/pizza/specialty.html
{% extends "pizza/base.html" %}

{% block body %}
<div class="specialtypizza">
    <h1>{{ name }}</h1>
        <form action="{% url 'pizza:pizza' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="pk" value="{{ pk }}"/>
            <input type="hidden" name="category" value="{{ category }}"/>
            <div class="form-group">
                <label for="size">Select a Size</label>
                <select class="form-control" id="size" name="size">
                    {% for i in prices %}
                    <option value="{{ i.size }}">{{ i }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="quantity">Select a Quantity</label>
                <input class="form-control" type="number" value="{{ i.quantity }}" id="quantity" name="quantity" min="0">
            </div>
            <div class="form-group">
                <p align="center"><button class="btn btn-primary">Add to Cart</button></p>
            </div>
        </form>

</div>

{% endblock %}