Richard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('home.urls')),
	path('pizza', include('pizza.urls', namespace="pizza")),
    path('primer', include('primer.urls', namespace="primer")),    
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path
from . import views

# Create your views here.
urlpatterns = [
	path("", views.index, name="index")
]

primer/urls.py
from django.urls import path
from . import views

# Create your views here.
app_name = "primer"
urlpatterns = [
	path("<int:week>", views.primer, name="primer"),
	path("<int:week>/comment", views.comment, name="comment")
]

primer/models.py
from django.db import models

# Create your models here.
class ThursdayGame(models.Model):
	week = models.IntegerField()
	team1 = models.CharField(max_length=64)
	team1image = models.CharField(max_length=64)
	team2 = models.CharField(max_length=64)
	team2image = models.CharField(max_length=64)
	time = models.CharField(max_length=64)
	network_image = models.CharField(max_length=64)

class FridayGame(models.Model):
	week = models.IntegerField()
	team1 = models.CharField(max_length=64)
	team1image = models.CharField(max_length=64)	
	team2 = models.CharField(max_length=64)
	team2image = models.CharField(max_length=64)	
	time = models.CharField(max_length=64)
	network_image = models.CharField(max_length=64)	

class SaturdayGame(models.Model):
	week = models.IntegerField()
	team1 = models.CharField(max_length=64)
	team1image = models.CharField(max_length=64)	
	team2 = models.CharField(max_length=64)
	team2image = models.CharField(max_length=64)	
	time = models.CharField(max_length=64)
	network_image = models.CharField(max_length=64)	

class SundayGame(models.Model):
	week = models.IntegerField()
	team1 = models.CharField(max_length=64)
	team1image = models.CharField(max_length=64)	
	team2 = models.CharField(max_length=64)
	team2image = models.CharField(max_length=64)	
	time = models.CharField(max_length=64)
	network_image = models.CharField(max_length=64)	

class MondayGame(models.Model):
	week = models.IntegerField()
	team1 = models.CharField(max_length=64)
	team1image = models.CharField(max_length=64)	
	team2 = models.CharField(max_length=64)
	team2image = models.CharField(max_length=64)	
	time = models.CharField(max_length=64)
	network_image = models.CharField(max_length=64)

class Media(models.Model):
	week = models.IntegerField()
	title = models.CharField(max_length=64)	
	entry_image = models.CharField(max_length=64, blank=True)	
	entry = models.TextField()
	hottake = models.TextField()

class Comment(models.Model):
	name = models.CharField(max_length=64)
	comment = models.TextField()
	date = models.DateTimeField(auto_now_add=True)
	week = models.IntegerField()

primer/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from .models import ThursdayGame, FridayGame, SaturdayGame, SundayGame, MondayGame, Media, Comment

# Create your views here.
def primer(request, week):
	context = {
		"thugames": ThursdayGame.objects.filter(week=week),
		"frigames": FridayGame.objects.filter(week=week),
		"satgames": SaturdayGame.objects.filter(week=week),
		"sungames": SundayGame.objects.filter(week=week),
		"mongames": MondayGame.objects.filter(week=week),
		"media": Media.objects.filter(week=week),
		"comments": Comment.objects.filter(week=week).order_by('date'),
		"week": week
	}
	return render(request, "primer/primer.html", context)

def comment(request, week):
	name = request.POST["name"]
	comment = request.POST["comment"]
	c = Comment(name=name, comment=comment, week=week)
	c.save()

	return redirect("primer:primer", week=week)

primer/templates/primer/layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>The Menu - A Sports and Media Primer</title>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'primer/css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Contrail+One" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
</head>
<body>
	<a class="navbar-brand" href="#"><img src="{% static 'primer/assets/' %}TheMenu.png" alt="The Menu" height="20px" width="auto"></a>
	<div class="dropdown">
  		<button class="dropbtn">Week</button>
  		<div class="dropdown-content">
    		<a href="{% url 'primer:primer' week=1 %}">Week 1</a>
    		<a href="{% url 'primer:primer' week=2 %}">Week 2</a>
    		<a href="{% url 'primer:primer' week=3 %}">Week 3</a>
			<a href="{% url 'primer:primer' week=4 %}">Week 4</a>
			<a href="{% url 'primer:primer' week=5 %}">Week 5</a>			
			<a href="{% url 'primer:primer' week=6 %}">Week 6</a>
			<a href="{% url 'primer:primer' week=7 %}">Week 7</a>	
			<a href="{% url 'primer:primer' week=8 %}">Week 8</a>
			<a href="{% url 'primer:primer' week=9 %}">Week 9</a>			
			<a href="{% url 'primer:primer' week=11 %}">Week 11</a>			
			<a href="{% url 'primer:primer' week=12 %}">Week 12</a>
			<a href="{% url 'primer:primer' week=13 %}">Week 13</a>
			<a href="{% url 'primer:primer' week=14 %}">Week 14</a>			
  		</div>
  		<div class="carousel">
  			<p>UPCOMING FILMS:</p>
  		</div>
		<div class="carousel">
  			<p>Glass, Jan 18</p>
  		</div>
  		<div class="carousel">
  			<p>Alita: Battle Angel, Feb 14</p>
  		</div>
  		<div class="carousel">
  			<p>How to Train Your Dragon 3, Feb 22</p>
  		</div>
  		<div class="carousel">
  			<p>Captain Marvel, Mar 8</p>
  		</div>  		  		
	</div>

	<div id="sports">
		<div class="container">	
			<h2>Sports</h2>
			<table class="table" style="width:100%">
	{% block sports %}
	{% endblock %}
			</table>
		</div>
	</div>

	<div id="media">
		<div class="container">	
			<h2>Media</h2>
	{% block media %}
	{% endblock %}
		</div>
	</div>

	<div id="comments">
		<div class="container">	
			<h2>Comments</h2>
	{% block comments %}
	{% endblock %}
		</div>
	</div>

	<script src="{% static 'primer/javascript/primer.js' %}"></script>
</body>
</html>

primer/templates/primer/primer.html
{% extends "primer/layout.html" %}
{% load static %}

{% block sports %}
{% if thugames %}
<thead>
	<td colspan="3">Thursday</td>
</thead>
<tbody>
	{% for game in thugames %}
	<tr>
	    <td class="left">
	    	<img class="logo" alt="{{ game.team1 }}" src="{% static 'primer/assets/' %}{{ game.team1image }}">
	    	<span class="left">{{ game.team1 }}</span>
	    </td>
    	<td class="center">
    		<img class="network" alt="CBSSN" src="{% static 'primer/assets/' %}{{ game.network_image }}">
    		<p>{{ game.time }}</p>
    	</td>
    	<td class="right">
    		<span class="right">{{ game.team2 }}</span>
    		<img class="logo" alt="{{ game.team2 }}" src="{% static 'primer/assets/' %}{{ game.team2image }}">
    	</td>
	</tr>
	{% endfor %}
</tbody>
{% endif %}

{% if frigames %}	
<thead>
	<td colspan="3">Friday</td>
</thead>
<tbody>
	{% for game in frigames %}
	<tr>
	    <td class="left">
	    	<img class="logo" alt="{{ game.team1 }}" src="{% static 'primer/assets/' %}{{ game.team1image }}">
	    	<span class="left">{{ game.team1 }}</span>
	    </td>
    	<td class="center">
    		<img class="network" alt="CBSSN" src="{% static 'primer/assets/' %}{{ game.network_image }}">
    		<p>{{ game.time }}</p>
    	</td> 
    	<td class="right">
    		<span class="right">{{ game.team2 }}</span>
    		<img class="logo" alt="{{ game.team2 }}" src="{% static 'primer/assets/' %}{{ game.team2image }}">
    	</td>
	</tr>
	{% endfor %}
</tbody>
{% endif %}

{% if satgames %}	
<thead>
	<td colspan="3">Saturday</td>
</thead>
<tbody>
	{% for game in satgames %}
	<tr>
	    <td class="left">
	    	<img class="logo" alt="{{ game.team1 }}" src="{% static 'primer/assets/' %}{{ game.team1image }}">
	    	<span class="left">{{ game.team1 }}</span>
	    </td>
    	<td class="center">
    		<img class="network" alt="CBSSN" src="{% static 'primer/assets/' %}{{ game.network_image }}">
    		<p>{{ game.time }}</p>
    	</td> 
    	<td class="right">
    		<span class="right">{{ game.team2 }}</span>
    		<img class="logo" alt="{{ game.team2 }}" src="{% static 'primer/assets/' %}{{ game.team2image }}">
    	</td>
	</tr>
	{% endfor %}
</tbody>
{% endif %}

{% if sungames %}	
<thead>
	<td colspan="3">Sunday</td>
</thead>
<tbody>
	{% for game in sungames %}
	<tr>
	    <td class="left">
	    	<img class="logo" alt="{{ game.team1 }}" src="{% static 'primer/assets/' %}{{ game.team1image }}">
	    	<span class="left">{{ game.team1 }}</span>
	    </td>
    	<td class="center">
    		<img class="network" alt="CBSSN" src="{% static 'primer/assets/' %}{{ game.network_image }}">
    		<p>{{ game.time }}</p>
    	</td> 
    	<td class="right">
    		<span class="right">{{ game.team2 }}</span>
    		<img class="logo" alt="{{ game.team2 }}" src="{% static 'primer/assets/' %}{{ game.team2image }}">
    	</td>
	</tr>
	{% endfor %}
</tbody>
{% endif %}

{% if mongames %}	
<thead>
	<td colspan="3">Monday</td>
</thead>
<tbody>
	{% for game in mongames %}
	<tr>
	    <td class="left">
	    	<img class="logo" alt="{{ game.team1 }}" src="{% static 'primer/assets/' %}{{ game.team1image }}">
	    	<span class="left">{{ game.team1 }}</span>
	    </td>
    	<td class="center">
    		<img class="network" alt="CBSSN" src="{% static 'primer/assets/' %}{{ game.network_image }}">
    		<p>{{ game.time }}</p>
    	</td> 
    	<td class="right">
    		<span class="right">{{ game.team2 }}</span>
    		<img class="logo" alt="{{ game.team2 }}" src="{% static 'primer/assets/' %}{{ game.team2image }}">
    	</td>
	</tr>
	{% endfor %}
</tbody>
{% endif %}
{% endblock %}

{% block media %}
{% if media %}
<div class="row">
	{% for item in media %}
	<div class="col-lg-4 col-sm-6">
		<div class="entry">
			<img src="{% static 'primer/assets/' %}{{ item.entry_image }}">
			<h3>{{ item.title }}</h3>
			<p>{{ item.entry }}</p>
			<div class="text-center hottake"><i class="fa fa-angle-down"></i></div>
			<p style='display:none'>{{ item.hottake }}</p>
		</div>
	</div>
	{% endfor %}
</div>
{% else %}
<h3><img id="yoda" src="{% static 'primer/assets/' %}yoda.png"></h3>
<h4 style="text-align: center">Patience you must have, my young Padawan</h4>
{% endif %}
{% endblock %}

{% block comments %}
{% for com in comments %}
<div class="comment_entry">
	<p class="author">{{ com.name }} says:</p>
	<p class="comment">{{ com.comment }}</p>
	<hr>
</div>
{% endfor %}

<form action="{% url 'primer:comment' week %}" method="post">
	{% csrf_token %}
	<div class="form-group row">
		<div class="col-sm-4">
			<label for="name-input">Your Name:</label>
			<input class="form-control" type="text" name="name" id="name">
		</div>
	</div>
	<div class="form-group row">
		<div class="col-sm-12">
			<label for="comment-input">Your Own Hot Take:</label>
			<textarea class="form-control" name="comment" id="comment" rows="5"></textarea>
	</div>
	</div>
	<div class="form-group">
		<p align="right"><button class="btn btn-primary">Submit</button></p>
	</div>
</form>
{% endblock %}